import logging

SENSOR_SLEEP_TIME = 0.2
WATCHER_SLEEP_TIME = 5
SENSOR_ERROR_SLEEP_TIME = 1
BASE_URL = "http://192.168.0.107:8080/"
BASE_API_URL = BASE_URL + "api/"
SENSOR_API_URL = BASE_API_URL + "sensors/"
DEVICE_API_URL = BASE_API_URL + "devices/"


MQTT_ADDRESS = "192.168.0.107"



LOG_RULES = {
    "SYSTEM": logging.WARNING,
    "SENSOR": logging.WARNING,
    "DEVICE": logging.WARNING,
    "THREAD": logging.WARNING,
}