import logging

SENSOR_SLEEP_TIME = 0.2
WATCHER_SLEEP_TIME = 5
SENSOR_ERROR_SLEEP_TIME = 1
BASE_API_URL = "http://192.168.0.117:8080/"
SENSOR_API_URL = BASE_API_URL + "sensors/"
DEVICE_API_URL = BASE_API_URL + "devices/"


MQTT_ADDRESS = "192.168.0.117"



LOG_RULES = {
    "SYSTEM": logging.INFO,
    "SENSOR": logging.INFO,
    "DEVICE": logging.INFO,
}