"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SensorReading(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DELTA_MS_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    delta_ms: _builtins.int
    """diferença em ms desde o timestamp base"""
    value: _builtins.float
    def __init__(
        self,
        *,
        delta_ms: _builtins.int = ...,
        value: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delta_ms", b"delta_ms", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SensorReading: _TypeAlias = SensorReading  # noqa: Y015

@_typing.final
class SensorReadingBatch(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BASE_TIMESTAMP_FIELD_NUMBER: _builtins.int
    READINGS_FIELD_NUMBER: _builtins.int
    base_timestamp: _builtins.int
    """timestamp da primeira leitura"""
    @_builtins.property
    def readings(self) -> _containers.RepeatedCompositeFieldContainer[Global___SensorReading]:
        """cada leitura só carrega o delta"""

    def __init__(
        self,
        *,
        base_timestamp: _builtins.int = ...,
        readings: _abc.Iterable[Global___SensorReading] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base_timestamp", b"base_timestamp", "readings", b"readings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SensorReadingBatch: _TypeAlias = SensorReadingBatch  # noqa: Y015
